### ISSUE TITLE
performance issue about lager on yaws web server with  file backend  [JIRA: RIAK-1863]

### ISSUE THREAD

**Issue by ajiyoshi** [erlang-lager/lager#133]
Hi.

Now, I'm trying  some logging tools for my advertising system.
I benchmarked log4erl, error_logger and lager.  
I try to write some simple application log to file from [yaws](http://yaws.hyber.org/) (an erlang web server) application.

result in lager was 100+ times slower than others.

did I make any miss configuration or insane use of lager?
[entire my benchmark code is here](https://github.com/ajiyoshi/lager_bench/tree/e903bccc0dd9ac1ba75ba8bde6ca79404ea7cf82)

each benchmark code are blow. ( these are [appmods](http://yaws.hyber.org/appmods.yaws) on [embedded yaws](http://yaws.hyber.org/embed.yaws) ).
- [lager](https://github.com/ajiyoshi/lager_bench/blob/e903bccc0dd9ac1ba75ba8bde6ca79404ea7cf82/src/appmod_with_lager.erl)
- [error_handler](https://github.com/ajiyoshi/lager_bench/blob/e903bccc0dd9ac1ba75ba8bde6ca79404ea7cf82/src/appmod_without_lager.erl)
- [log4erl](https://github.com/ajiyoshi/lager_bench/blob/e903bccc0dd9ac1ba75ba8bde6ca79404ea7cf82/src/appmod_log4erl.erl)

ab result:

```
lagger
Requests per second:    47.78 [#/sec] (mean)

error_handler
Requests per second:    8138.14 [#/sec] (mean)

log4erl
Requests per second:    7291.94 [#/sec] (mean)
```
- [lager config is such like this](https://github.com/ajiyoshi/lager_bench/blob/e903bccc0dd9ac1ba75ba8bde6ca79404ea7cf82/src/logger_config.erl)
- I use latest lager (master branch on github)
- I use "ab" command  (a HTTP benchmark tool A.K.A. apache bench ) to benchmark.
  - ab's concurrency level is 10 (this is not so heavy condition for our advertising server).
- Erlang VM " Erlang R15B01 (erts-5.9.1) [source] [64-bit] [smp:4:4] [async-threads:0] [kernel-poll:false] "
- benchmark on Debian 3.2.32-1 with Intel(R) Core(TM)2 Quad CPU    Q9550  @ 2.83GHz
  - the machine is slow. but i think this is NOT machine power issue.

**Comment by jacktang** [comment]
I came across the same performance issue. And find the solution by setting `sync_on` level higher. Read the code:
https://github.com/basho/lager/blob/master/src/lager_file_backend.erl#L226, and why does lager set the sync_on level? it is harmful to the performance, right?

**Comment by Vagabond** [comment]
Because un-synched messages will be lost if the node crashes, so it is usually better to take the performance hit to ensure you have logs that describe what happened before the node crashed.
