### ISSUE TITLE
Traces from config file do not work if same file backend is not used for a handler

### ISSUE THREAD

**Issue by srijan** [erlang-lager/lager#158]
`lager_app:add_configured_traces/0` calls `lager:trace/3` to add the configured traces, which **does not handle the case of the file backend not installed**. So, those traces don't work.

Either `add_configured_traces/0` should call `lager:trace_file/3` in case of `lager_file_backend`, or `trace/3` should handle file backend same as `trace_file/3`.

If someone can tell me what is the preferred structure, I can also send a pull request.

**Comment by mrallen1** [comment]
@macintux Do you remember if this is still a problem? I know we spent a good bit of time looking at how to make tracing more consistent from configuration files.

**Comment by mrallen1** [comment]
Looks like this fix was committed a while ago. Not sure why this is still open. Going to close. Please reopen if it's a problem.
