### ISSUE TITLE
Trace filters broken

### ISSUE THREAD

**Issue by supersasha** [erlang-lager/lager#159]
Suppose I wish to add a trace where all events should get. I create filter {null, true}. When I validate trace using lager_utils:validate_trace -> lager_utils:validate_trace_filter it appears filter MUST be a list!

OK, I try to use [{null, true}], but when a list is provided it is pre-processed with trace_all/1 which applies trace_acc/1 which in turn transforms {null, true} into glc:eq(null, true) ({null, '=', true}) instead of glc:null(true).

**Comment by mrallen1** [comment]
This is something that needs some investigation around getting "everything" - this is still an issue AFAIK. It should be reasonably easy to fix though and there's a PR with suggested code that's worth looking at.

**Comment by mrallen1** [comment]
Since I merged #389, I'm going to close this issue.
