### ISSUE TITLE
Fix config instructions in README

### ISSUE THREAD

**Issue by plainlystated** [erlang-lager/lager#174]
The README says to add something to my app's <app>.config to configure lager [1].  Lager, however, doesn't seem to look at my app's config, but rather at its own [2]. All the examples I've found of people using lager actually set the config via code, not in the app.config (eg [3]).

Following the README, I haven't been able to get the non-default behavior. Am I missing something?

Thanks,
Patrick 

[1] https://github.com/basho/lager#configuration
[2] https://github.com/basho/lager/blob/master/src/lager_app.erl#L65
[3] https://github.com/basho/riak_test/blob/master/src/riak_test_escript.erl#L107

**Comment by mrallen1** [comment]
Since lager has changed a lot since this issue was opened I'm going to close it. Please reopen if needed.
