### ISSUE TITLE
lager usage on slave nodes

### ISSUE THREAD

**Issue by dorny** [erlang-lager/lager#190]
Hi,
I'm not sure how i should use lager in distributed environment (using slave module).

If lager:start() is not called on slave node, logging not work.
Lager uses localy registered name 'lager_event' and nammed ets table for config. It seems to me, lager was not designed to automatically collect log on master node from slave nodes (it would be great if this can be optionally turned on).

If lager:start() is called on worker node, at start it print errors:
"[error] Failed to open log file log/error.log with error no such file or directory"
Slave module performs auto redirect of I/O and slave node uses file system of master node.
If file is open with raw option, what lager do, filesystem redirect is turned off.
After some testing i've figured out file:open() on slave node works only with absolute paths. I checked working dir, so i'm absolute sure about this.

I have changed lager_util:open_logfile so it uses absolute path. Logging work, log files are stored on slave nodes, console logs are visible on master node and no error messages on startup. Should i open pull request or i totally misunderstood something?
I'm using R16B02.

Thanks.

**Comment by mrallen1** [comment]
Due to the age of this issue I am closing it. Please reopen if needed.
