### ISSUE TITLE
lager.app env overwrites default handlers

### ISSUE THREAD

**Issue by fogfish** [erlang-lager/lager#215]
application:start(lager) applies all lager setting to application env, including default handlers
            {handlers, [
                {lager_console_backend, info},
                {lager_file_backend, [
                    {file, "log/error.log"}, {level, error}, {size, 10485760}, {date, "$D0"}, {count, 5}]},
                {lager_file_backend, [
                    {file, "log/console.log"}, {level, info}, {size, 10485760}, {date, "$D0"}, {count, 5}]}
            ]},

Unfortunately, it also overwrites handlers configured by the application. The proposal is remove handlers from lager.app. The default handlers are installed anyway from lager_app.erl

**Comment by mrallen1** [comment]
Startup code changed considerably in 3.x. If this is still an issue, please reopen.
