### ISSUE TITLE
lager_console_backend on Windows

### ISSUE THREAD

**Issue by thehangedman** [erlang-lager/lager#217]
Hi,

the following commit:
https://github.com/basho/lager/commit/032b3fc518bbe6db3f08bc71e0807e07ac566587
broke lager_console_backend on Windows. 
(Apart from this, the condition "element(1, os:type()) /= win32" is evidently a bad choice for checking if the new shell is present)

The previous commit:
https://github.com/basho/lager/commit/59a2a1a974283a6972b64752fe394f9dcf6bc055
correctly allowed to use lager_console_backend on Windows with old shell because there's no alternative. The commit above for some reasons reverts the condition and breaks this useful behaviour. Please change it back, if possible.

**Comment by mrallen1** [comment]
Due to the age of this issue, I'm closing it. Please reopen if it's still broken.
