### ISSUE TITLE
lager (master/HEAD) vs. relx (master/HEAD)

### ISSUE THREAD

**Issue by Cloven** [erlang-lager/lager#221]
installing lager as a dependency via rebar:

{sub_dirs, ["apps/jobmachine"]}.
{deps_dir, ["deps"]}.
{deps, [
  {eredis, "._", {git, "git://github.com/wooga/eredis.git"}},
  {lager, "._", {git, "git://github.com/basho/lager.git"}},
  {folsom, ".*", {git, "git://github.com/boundary/folsom.git"}}
]}.

lager builds fine, and starts fine via the command line:

erl -pa deps/*/ebin
Erlang/OTP 17 [erts-6.0] [source] [64-bit] [smp:2:2] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V6.0  (abort with ^G)
3> application:start(syntax_tools).
ok
5> application:start(compiler).
ok
6> application:start(goldrush).
ok
7> application:start(lager).
ok
8> 19:29:39.248 [info] Application lager started on node nonode@nohost

but when I use relx with what I believe to be the simplest possible relx.config to build a node release that starts lager:

{extended_start_script, true}.
{default_release, jobmachinenode, "0.0.1"}.
{release, {jobmachinenode, "0.0.1"}, [jobmachine, lager, runtime_tools]}.

and then run _rel/bin/jobmachinenode console, I get:

18:16:03.066 [error] CRASH REPORT Process <0.46.0> with 0 neighbours exited with reason: {compile_forms,error} in glc_code:compile_forms/2 line 347 in application_master:init/4 line 133
18:16:03.066 [info] Application lager exited with reason: {compile_forms,error} in glc_code:compile_forms/2 line 347
{"Kernel pid terminated",application_controller,"{application_start_failure,lager,{bad_return,{{lager_app,start,[normal,[]]},{'EXIT',{{compile_forms,error},[{glc_code,compile_forms,2,[{file,\"src/glc_code.erl\"},{line,347}]},{glc_code,compile,2,[{file,\"src/glc_code.erl\"},{line,30}]},{glc,compile,2,[{file,\"src/glc.erl\"},{line,171}]},{lager_util,trace_filter,2,[{file,\"src/lager_util.erl\"},{line,364}]},{lager_app,start,2,[{file,\"src/lager_app.erl\"},{line,101}]},{application_master,start_it_old,4,[{file,\"application_master.erl\"},{line,272}]}]}}}}}"}

It's unclear whether this is a lager issue, goldrush issue, compile module issue, relx issue, or pebkac issue, but this error is particularly inscrutable and, to me, intractable so far.

**Comment by mrallen1** [comment]
This is definitely related to goldrush needing the compile tools.  Is this still an issue? If so, please reopen.
