### ISSUE TITLE
can lager support user defined level name [JIRA: RIAK-1895]

### ISSUE THREAD

**Issue by tianxiao-ma** [erlang-lager/lager#230]
Hi, @jaredmorrow 

In my situation, I need to log some thing into a file, so such file can be analysed later. But I don't want to use the level defined by lager, I want to use a customized level name(etc. `lager:my_log("some useful informaion")`).  Like log4j in java, it allowed user to defined a "log name" for each Log object, so the "log name" can be used in application code to found the Log object.

I have read the source code, and found lager only support predefined level. Will lager support user-defined level or something like this in the future?

**Comment by mrallen1** [comment]
Hi we could look into supporting something like this in the future, but there'd have to be a way to map the "custom" log level to a "real" level.

**Comment by mrallen1** [comment]
In the 3.x branch we have multiple sink support which implements something similar to this without needing to define custom log levels. Instead you can define sink names which can output information to a backend using whatever controls you want to associate with them.

So I'm going to close this issue.  Please reopen if it doesn't address what use case you have in mind. Thanks.
