### ISSUE TITLE
Options for load-shedding? [JIRA: RIAK-1889]

### ISSUE THREAD

**Issue by rlipscombe** [erlang-lager/lager#243]
We had an issue in production where for as-yet-undiscovered reasons, our syslog daemon (and therefore lager_syslog_backend) started being really slow.

What options, if any, do we have for load-shedding (i.e. simply dropping log messages), either on a per-backend or global basis?

I'm thinking that a wrapper backend that shovels messages to another pid, while watching the message queue length, would work. We'd need some kind of gen_event wrapper to turn the messages into handle_event, calls though, obviously.

Any other ideas?

**Comment by mrallen1** [comment]
Combine with #256

**Comment by mrallen1** [comment]
We are working on adding #328 which will address this concern.

**Comment by mrallen1** [comment]
We did merge the gen_event killer, so I'm going to close this.
