### ISSUE TITLE
Overload protection may cause process leak [JIRA: RIAK-1675]

### ISSUE THREAD

**Issue by linbo** [erlang-lager/lager#256]
Hi,

We hit a process leak when using lager. Here is the scenario:

Application spawn lots of process, lager used to handle logs. When mailbox size exceeds the threshold, it will use synchronous mode. But here may cause a problem, process continue produce logs, it will be blocked in lager handle logs in synchronous mode, then more and more processes hang, as a result process leak happened.

We add a option to prevent this issue, if mailbox exceeds an discard threshold, just discard logs simply.  The latest two commit of our fork is the change (https://github.com/yunba/lager/commits/master).

Can official repo provide a solution, since we won't want to manage multi repos for lager.

**Comment by mrallen1** [comment]
I like this idea, but it will have to wait for a future release.

**Comment by mrallen1** [comment]
We are working on adding #328 which will address the same concern (in a different way of course.)
