### ISSUE TITLE
each logger have and id can be set [JIRA: RIAK-1777]

### ISSUE THREAD

**Issue by ChinaXing** [erlang-lager/lager#261]
hope the logger can set and id filed : 

`{{lager_file_backend, [{id, router_log}, {file, "router_error.log"}, {level, error}]}`

then it can be referenced from traces : 

`{router_log, [{module, am}], info}`

**Comment by mrallen1** [comment]
The forthcoming 3.x branch supports multiple sinks with multiple independent traces. Seems to provide some of what you're asking for here.
