### ISSUE TITLE
parse_transform must be the first line opiton of erl_opts [JIRA: RIAK-1833]

### ISSUE THREAD

**Issue by xuthief** [erlang-lager/lager#268]
{parse_transform, lager_transform} has to be located at the head of erl_opts in rebar.config,
otherwise lager will terminate with the following error output:
{'EXIT',{undef,[{lager,info,[\"start ~p\",[1]],[]}

**Comment by mrallen1** [comment]
Hi - that's strange - perhaps you have an old rebar?  I haven't seen that problem with our builds. Can you provide more details?

**Comment by mrallen1** [comment]
Any further information on this ticket? If not I will close it after 7 days.
