### ISSUE TITLE
Have high water mark work with any handler [JIRA: RIAK-2093]

### ISSUE THREAD

**Issue by walrusVision** [erlang-lager/lager#285]
Currently it looks like the highwater mark is dependent on the back end implementing it. It seems like its generic enough use case that it would be useful for this to be back end independent and then you could apply a highwater mark to any handler without worrying if it supports it or not.

**Comment by mrallen1** [comment]
It doesn't make sense for all backends to implement this functionality, imo. Making it *possible* to include it in your own backends seems like a good first step. :smile:

**Comment by walrusVision** [comment]
> Making it possible to include it in your own backends seems like a good first step. :smile:

Some nice helper functions to make processing configs on the backends easier or a function to determine whether to send the message or not?

In the meantime at least I might have to start looking writing some patches then!

**Comment by mrallen1** [comment]
We made high water mark checking available in arbitrary handlers in commit e1a2907d5c2fdc8b2d938c67a391673a478ee38b. You can see the code changes needed to use it in your own handler.
