### ISSUE TITLE
More consistent sink name usage  [JIRA: RIAK-2109]

### ISSUE THREAD

**Issue by walrusVision** [erlang-lager/lager#287]
It would be nice if the sink name usage was more consistent and you didn't have to use a mix of internal and non-internal sink names.

For example in code and rebar config you use one sink name e.g. `audit`. But in the config file and passing to functions you have to use the internal sink name e.g. `audit_lager_event`.

However the documentation and readme doesn't reflect this. For example for the [trace example in the readme](https://github.com/basho/lager/blob/3.0.1/README.md#multiple-sink-support) for multiple sinks says to use the option `{sink, audit}` which would fail with `{error,noproc}`. To work it would have to be `{sink, audit_lager_event}`.

**Comment by mrallen1** [comment]
Yes, good point. We should definitely update the documentation.
