### ISSUE TITLE
Add 'node' as an option to `lager_default_formatter`

### ISSUE THREAD

**Issue by rlipscombe** [erlang-lager/lager#309]
We've had to write a custom lager formatter because we wanted the node name to appear in the log. If `lager_default_formatter` supported (e.g.) `node` (analogous to `date`, `time`, `severity`, etc.) we could use the default formatter.

**Comment by mrallen1** [comment]
Thanks for the feedback. I think we ought to add that in a future release too.

**Comment by seriyps** [comment]
But it's already supported, isn't it?

https://github.com/basho/lager#custom-formatting

> The placeholders pid, file, line, module, function, and node will always exist if the parse transform is used.

**Comment by rlipscombe** [comment]
Apparently, it _is_ -- there's even a unit test for it in `lager_console_backend.erl`. I have no idea how I missed that.

**Comment by rlipscombe** [comment]
I'm going to reopen this; it needs further investigation. In lager 3.2.1 (and possibly more recently), if I use the following config:

```
[date, " ", time, " ", node, " ", color, "[", severity, "]", ...
```

...then the `node` is often displayed as `Undefined`, particularly in the initial startup messages. If, instead, I use the following:

```
[date, " ", time, " ", {node, atom_to_list(node())}, " ", color, "[", severity, "]", ...
```

...then it works as expected.

Obviously, I can't use the second form in a configuration file, so I end up having to introduce a custom formatter module, as originally stated.

**Comment by mrallen1** [comment]
OK, thanks for the clarity. Hopefully someone can take a look at this soon.

**Comment by GeraldXv** [comment]
Any update?

**Comment by rlipscombe** [comment]
@mrallen1 yes, this seems to work. Thanks.
