### ISSUE TITLE
lager_event message queue growth  [JIRA: RIAK-2433]

### ISSUE THREAD

**Issue by blt** [erlang-lager/lager#324]
Hi folks!

We've hit instances where a burst of traffic into lager will cause the lager_event message queue to grow substantially, to the point where lager is still emptying out several hours later. This causes a system-wide slowdown as lager has switched synchronous mode to cope. 

A bit goofy, but something that's bit us a few times as our system has a bursty traffic pattern. 

I've put together a repository to reproduce, called [burst](https://github.com/blt/burst). You can see it in action here:

```
(burst@walden)1> spawn(burst, run, [10000,100]), recon:proc_window(message_queue_len, 10, timer:seconds(10)).
[{<0.311.0>,28728,
  [lager_event,
   {current_function,{lager_default_formatter,make_printable,
                                              1}},
   {initial_call,{proc_lib,init_p,5}}]},
 {<0.1040.0>,0,
  [{current_function,{gen,do_call,4}},
   {initial_call,{burst,wrkr,3}}]},
 {<0.1630.0>,0,
  [{current_function,{gen,do_call,4}},
   {initial_call,{burst,wrkr,3}}]},
 {<0.2220.0>,0,
  [{current_function,{gen,do_call,4}},
   {initial_call,{burst,wrkr,3}}]},
 {<0.2810.0>,0,
  [{current_function,{gen,do_call,4}},
   {initial_call,{burst,wrkr,3}}]},
 {<0.7981.0>,0,
  [{current_function,{gen,do_call,4}},
   {initial_call,{burst,wrkr,3}}]},
 {<0.8571.0>,0,
  [{current_function,{gen,do_call,4}},
   {initial_call,{burst,wrkr,3}}]},
 {<0.9161.0>,0,
  [{current_function,{gen,do_call,4}},
   {initial_call,{burst,wrkr,3}}]},
 {<0.3852.0>,0,
  [{current_function,{gen,do_call,4}},
   {initial_call,{burst,wrkr,3}}]},
 {<0.4442.0>,0,
  [{current_function,{gen,do_call,4}},
   {initial_call,{burst,wrkr,3}}]}]
```

The challenge we have is that there's not much control on the user side once `lager_event` backs up. For our use case, once you blow past some higher high-water-mark, it'd be desirable just to start dropping log messages, rather than pool them up for later emission. 

We'd be happy to do the work. Would this be in-line with lager's handling philosophy? 

/cc @JoseManuelRodriguez @miriampena

**Comment by mrallen1** [comment]
That's been on the wishlist for a while. There's currently an open PR #248 that kills the event handler and restarts it once it exceeds some threshold and both @macintux and I were ... unsure that was the right behavior. 

I think what you're proposing sounds more palatable. Do you have any thoughts @Vagabond?

**Comment by Vagabond** [comment]
I am open to either suggestion, if the logging pressure is that high you're kind of stuck.

**Comment by Vagabond** [comment]
Killing the worker is definitely the easier route.

**Comment by mrallen1** [comment]
@Vagabond Agreed on that. What do you think of #248?  We've been somewhat wary of it mostly due to the semantics of a kill/restart.

**Comment by blt** [comment]
For what it's worth, kill/restart would be sufficient for our needs.

**Comment by mrallen1** [comment]
@blt If y'all want to rebase #248 against 3.1.0 and try it out, I would be grateful for the work and feedback on its efficacy.

**Comment by blt** [comment]
@mrallen1 It's a plan. Expect I'll get back to you later in the day.

**Comment by mrallen1** [comment]
:candy: thanks!

**Comment by mrallen1** [comment]
As this has been merged, I'm going to close it.
