### ISSUE TITLE
A C interface to lager [JIRA: RIAK-2537]

### ISSUE THREAD

**Issue by mrallen1** [erlang-lager/lager#351]
@Vagabond I heard you were at some point contemplating a C layer to route messages from things like leveldb into a lager sink. I was wondering if you had any suggestions about how that should be constructed (port driver/NIF/something else?) 

I have seen _plenty_ of libraries that show how to send messages **out** of Erlang into C land, but almost none showing how to send messages **from** C land into Erlang.  Thanks for any pointers or suggestions you may have.

**Comment by Vagabond** [comment]
I don't remember this. I suspect linked-in-drivers and NIFs would have a way to send messages to an erlang process, but I haven't poked around in those APIs recently.
