### ISSUE TITLE
Formatting fails on certain characters

### ISSUE THREAD

**Issue by whitfin** [erlang-lager/lager#358]
I've just started using Lager so I can't do much to investigate, but I've caught a bug with special chars:

```
1> lager:log(info, self(), "testµs")
[2016-05-17] [00:40:40.835] [info] testÂµs
```

I hope I got the syntax right, I'm using from Elixir and I believe that's how it translates (I've already checked this isn't an Elixir issue).

Might there be some option I'm missing or some sanitization I can do?

**Comment by mrallen1** [comment]
Dup of #330 

Lager's truncation system does not properly handle Unicode at this time.

**Comment by mrallen1** [comment]
Looks like #417 fixes this problem. So I'm going to close this ticket.
