### ISSUE TITLE
Lager gets stuck on io:execute_request

### ISSUE THREAD

**Issue by martinsk** [erlang-lager/lager#379]
We are experiencing lager getting getting stuck, and when looking inspecting the process we see that  it is waiting on current_function,{io,execute_request,2}

I also see that there is a high watermark killer in lager - but since the process is actually getting stuck the high watermark killer is never getting triggered - and even if it did, it sends a {"kill_me"  [_,_]} message which turns into a message on the queue, and since the queue isn't being consumed this doesn't really make a difference.

We are experiencing this on lager 3.2.1

**Comment by macintux** [comment]
Thanks for the bug report. What OS and OTP release?

You should take a look at #301. This sounds like a platform bug we've seen before in other contexts.

**Comment by Vagabond** [comment]
My guess is a stalled console, try disabling the lager_console_backend?

**Comment by mrallen1** [comment]
Any update on this?  If we don't hear back by our next triage in February, I will close this ticket.

**Comment by martinsk** [comment]
@mrallen1  I'm sorry I didn't get back @Vagabond was right - the setup was logging to the console and the logs were getting picked up by another service ... and the console would get stuck.. we started writing to files - and everything got better :)
