### ISSUE TITLE
Capture process lager_metadata in error_logger handler and pass it on as metadata to lager itself

### ISSUE THREAD

**Issue by Vagabond** [erlang-lager/lager#382]
When a process that has set lager metadata crashes, we should, in the error_logger handler, capture that dictionary and pass it to lager again.

**Comment by mrallen1** [comment]
See https://github.com/erlang-lager/lager/blob/master/src/error_logger_lager_h.erl#L55
we'd add metadata there beyond just the pid

**Comment by Vagabond** [comment]
https://github.com/erlang-lager/lager/blob/master/src/error_logger_lager_h.erl#L307 actually implements this.
