### ISSUE TITLE
So, so many errors on tests with OTP-20

### ISSUE THREAD

**Issue by tburghart** [erlang-lager/lager#383]
Perhaps this is premature, but running eunit tests with OTP-20.0-rc0 are not pretty.
It appears the `gen_server` crash messages have changed significantly.
Whether this will be the case who OTP-20 is released is yet to be seen, but it's worth getting it on the radar.

**Comment by mrallen1** [comment]
Thanks for the report! Yeah I haven't taken OTP 20 for a spin yet but it's good to get a tracker for this.

**Comment by tburghart** [comment]
PR https://github.com/erlang-lager/lager/pull/385 contains changes that may be relevant to version-specific checks.

**Comment by mrallen1** [comment]
I just committed #410 which fixes all the tests for OTP 20-RC1. Thanks for the report!
