### ISSUE TITLE
File backend unit tests fail on R15

### ISSUE THREAD

**Issue by mrallen1** [erlang-lager/lager#393]
I noticed this when I was [running Travis-CI](https://travis-ci.org/erlang-lager/lager/jobs/205120930) on #391, the file backend unit tests are failing for R15 because it calls `file:list_dir_all/1` which doesn't exist in that OTP release.

That break was introduced in #384.

**Comment by Vagabond** [comment]
I strongly suggest we drop R15 and R16 support, I think "last two major OTP releases" should be good enough for most people. If someone wants to use R15, they can always also use an older release.

**Comment by mrallen1** [comment]
I think we should get everything 100% green from the last set of merges and then announce we're dropping support for R15 and 16. Especially with OTP 20 on the horizon - suspect it's going to ship at/around Erlang Factory at the end of March.
