### ISSUE TITLE
erlang-lager/lager on hex.pm

### ISSUE THREAD

**Issue by lucafavatella** [erlang-lager/lager#400]
https://hex.pm/packages/lager points to basho/lager . Is this expected or shall it point to this repo? I am aware of #349.

(See also https://github.com/basho/lager/pull/2#issuecomment-292541801 )

**Comment by lucafavatella** [comment]
A relevant example seems https://github.com/basho/riak-erlang-client/commit/03668ae35fc0a2c0f20d3d58d152ad9087295f65

**Comment by mrallen1** [comment]
Thanks for the message! This should be considered the repo for new releases.

**Comment by mrallen1** [comment]
Also I guess the published version is pretty old. I will work on getting a new version published.

**Comment by mrallen1** [comment]
I just published 3.4.1 to hex.pm. Hope that helps.
