### ISSUE TITLE
Feature: Date format

### ISSUE THREAD

**Issue by doobinay** [erlang-lager/lager#401]
Hello, I'm using lager on multiple servers around the world, and they are logging with local time. 
Is there a way to format the date differently? For example I'd like to log with UTC formatted dates

I'm ok to try to implement it if necessary with some guidance!

**Comment by Vagabond** [comment]
Lager does support UTC logging, it is just not well documented.

https://github.com/erlang-lager/lager/blob/master/src/lager_stdlib.erl#L80

If you set the sasl, or stdlib, application variables, it should log UTC.

If you wanted to contribute, some documentation and testing would be nice (I haven't tried it in years).

**Comment by mrallen1** [comment]
Docs and test cases would be great, yes please.

**Comment by doobinay** [comment]
Works great, thank you! I'll open a PR this week.

**Comment by mrallen1** [comment]
Wonderful. Our regular monthly triage session is April 20, so if you get it finished by then we can review it during the triage meeting. Thanks!

**Comment by mrallen1** [comment]
Thanks for the patch and the issue!
