### ISSUE TITLE
make failed

### ISSUE THREAD

**Issue by qujian** [erlang-lager/lager#406]
i'm trying to make the master branch, and then got following
```shell
$ make
test -d deps || ./rebar get-deps
Uncaught error in rebar_core: {'EXIT',
                               {undef,
                                [{crypto,start,[],[]},
                                 {rebar,run_aux,2,[]},
                                 {rebar,main,1,[]},
                                 {escript,run,2,
                                  [{file,"escript.erl"},{line,757}]},
                                 {escript,start,1,
                                  [{file,"escript.erl"},{line,277}]},
                                 {init,start_em,1,[]},
                                 {init,do_boot,3,[]}]}}
Makefile:10: recipe for target 'deps' failed
make: *** [deps] Error 1
```

**Comment by mrallen1** [comment]
That failure suggests your Erlang installation does not support crypto and/or is not available from the paths in your shell environment.

**Comment by Vagabond** [comment]
Make sure your distribution has not defeated the point of the Erlang standard library and split Erlang into several packages. Check if there's an erlang-crypto (or something) package available, and install that as well.

**Comment by mrallen1** [comment]
Any further update on this issue?

**Comment by mrallen1** [comment]
OK, I am going to close this issue - please open a new one if you still need help. Thanks.
