### ISSUE TITLE
Tag 3.4.1 has app version 3.4.0

### ISSUE THREAD

**Issue by c-bik** [erlang-lager/lager#407]
[`lager.app.src`](https://github.com/erlang-lager/lager/blob/3.4.1/src/lager.app.src)
```erlang
...
{vsn, "3.4.0"}
...
```
Is it possible to fix the tag?

**Comment by mrallen1** [comment]
oh gosh. I sure messed that up. I fixed it in 805676f30403e1385429ab46b90eab698b20a806 but I didn't do a new tag. So let me push a new 3.4.2 tag now which will have the right version.

**Comment by mrallen1** [comment]
OK, 3.4.2 was pushed and published to hex.
