### ISSUE TITLE
Update list of backends in the README

### ISSUE THREAD

**Issue by Vagabond** [erlang-lager/lager#408]
We should figure out what backends/formatters are out there and add them to the README again.

I have a 'bunyan' formatter and a rollbar backend.

**Comment by Vagabond** [comment]
I don't know of a great list, but there are a bunch out there. There are several syslog ones (local syslog, remote syslog, syslog-ng), there's my rollbar backend (as mentioned before) my bunyan formatter (which is backend agnostic).

You can google or search github for 'lager backend' and a bunch show up. AMQP, airbrake, exometer, journald, etc. There's also some listed in Hex.

Maybe we could ask on erlang-questions for backends people use.

**Comment by mrallen1** [comment]
Adding some text about this in 3.6.0 release, so closing.
