### ISSUE TITLE
Why use parse_transform to wrap the call to lager:dispatch_log/6?

### ISSUE THREAD

**Issue by lintingbin2009** [erlang-lager/lager#413]
Hello, I feel very inconvenient in using {parse_transform, lager_transform}. So,  I have a question that "How much efficiency is improved by using parse_transform wrapping  the call to lager:dispatch_log/6?".

**Comment by mrallen1** [comment]
It's about twice as fast to use the parse_transform as it is to manually call lager:dispatch_log.  This is because the parse transform decides whether it ought to do something at the call site instead of copying terms for a remote function.

**Comment by mrallen1** [comment]
There hasn't been any new activity on this issue, so I'm going to close it for now. Please re-open if you have further questions about this topic.  Thanks.
