### ISSUE TITLE
Support for ranch 1.4.0

### ISSUE THREAD

**Issue by robertoaloi** [erlang-lager/lager#425]
Hi,

with the latest version of `ranch` (1.4.0) I noticed that `error_lager_lager_h` crashes with a case clause of the form:

```
[error] Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,...
```

This seems due to the fact that the _Event's Args_ returned by `ranch` are now of the form:

```
[Ref, Pid1, Integer, Pid2, Reason, Stacktrace]
```

I temporarily solved the situation by setting `error_logger_format_raw` to `true`, but you may want to adjust the case clauses to support the new format.

**Comment by mrallen1** [comment]
Thanks for the ticket. We will get this fixed in a future release!

**Comment by mrallen1** [comment]
I was working on this ticket today, but I can't find the code in ranch which emits the 5 element list as you describe it.  Do you have a better handle on where this this happening in `ranch`?

**Comment by robertoaloi** [comment]
Thanks for looking into this. It turns out that it is `cowboy` itself logging a "ranch-style" message and not `ranch` itself:

https://github.com/ninenines/cowboy/blob/2.2.2/src/cowboy_stream_h.erl#L206

**Comment by mrallen1** [comment]
Ah, ok. Thanks. Don't have to fix it today, but thank you for getting back so quickly.
