### ISSUE TITLE
automatically take effect

### ISSUE THREAD

**Issue by larrymeng** [erlang-lager/lager#433]
While the application is running, if I have changed the log configuration in app.config, 
can the lager can automatically take effect?

**Comment by mrallen1** [comment]
No, those settings are only pulled into the run-time at application start time.  You'd have to configure lager while it's running to match your `app.config` from an Erlang shell.

**Comment by mrallen1** [comment]
Going to close this issue now. Please open a new one if you still need help. Thank you.
