### ISSUE TITLE
Error: 'EXIT' function_clause lager_util:should_flush

### ISSUE THREAD

**Issue by marianoguerra** [erlang-lager/lager#437]
Lager 3.6.0

	Lager event handler error_logger_lager_h exited with reason 

	{'EXIT',{function_clause,[
	{lager_util,should_flush,[
	    {lager_shaper,error_logger_lager_h,50,50,
		{1516,404191,251790},0,false,0,
		#Ref<0.2498355355.3620470788.198399>,
		#Fun<error_logger_lager_h.2.54511703>}],
	    [{file,"_build/default/lib/lager/src/lager_util.erl"},{line,533}]},

	{lager_util,check_hwm,1,[{file,"_build/default/lib/lager/src/lager_util.erl"},{line,514}]},

	{error_logger_lager_h,handle_event,2,[{file,"_build/def..."},...]},...]}}

**Comment by mrallen1** [comment]
Think this was fixed in #436 - should be published later today.

**Comment by mrallen1** [comment]
Thanks for the report though!

**Comment by marianoguerra** [comment]
great, thanks!

**Comment by mrallen1** [comment]
Did this solve your problem Mariano?  If so, would you please close this issue?

**Comment by mrallen1** [comment]
@marianoguerra did #436 fix your issue? If I don't hear back in a week I'm going to close this issue.

**Comment by marianoguerra** [comment]
yes, fixed, thanks for the patience
