### ISSUE TITLE
Question: Why lager:log/3 prints FORMAT ERROR?

### ISSUE THREAD

**Issue by ethrbh** [erlang-lager/lager#444]
hello,

I am new in Lager, and I just did a test, by calling lager:log/ function. For same reason, I got FORMAT ERROR in the result, but checking the source code of the lager, I did not found anything what could be explain the result, and this is why I turned to you with this question.

Here is the test I did.

(igs@ethrbh-VirtualBox)1> lager:start().    
ok
(igs@ethrbh-VirtualBox)2> 
(igs@ethrbh-VirtualBox)2> 
(igs@ethrbh-VirtualBox)2> lager:log(info, self(), [{a,b,c}]).
ok
(igs@ethrbh-VirtualBox)3> 12:48:36.903 [info] FORMAT ERROR: [{a,b,c}] []

(igs@ethrbh-VirtualBox)3> 
(igs@ethrbh-VirtualBox)3> 
(igs@ethrbh-VirtualBox)3> application:which_applications().
[{igs,"Intelligent Gardening System","0.0.1"},
 {sasl,"SASL  CXC 138 11","3.0.4"},
 {runtime_tools,"RUNTIME_TOOLS","1.12"},
 {tools,"DEVTOOLS  CXC 138 16","2.10"},
 {observer,"OBSERVER version 1","2.4"},
 {erlang_ale_extension,"Extension for Erlang/ALE. Support more devices to control in Erlang.",
                       "0.1.2"},
 {erlang_ale,"Erlang/ALE - Erlang Actor Library for Embedded",
             "0.1.0"},
 {erwa,"a tiny WAMP router","2.0.0_pre"},
 {mnesia,"MNESIA  CXC 138 12","4.15"},
 {lager,"Erlang logging framework","3.2.2"},
 {goldrush,"Erlang event stream processor","0.1.9"},
 {syntax_tools,"Syntax tools","2.1.2"},
 {compiler,"ERTS  CXC 138 10","7.1"},
 {cowboy,"Small, fast, modern HTTP server.","2.0.0-rc.1"},
 {cowlib,"Support library for manipulating Web protocols.",
         "2.0.0-rc.1"},
 {ranch,"Socket acceptor pool for TCP protocols.","1.4.0"},
 {awre,"a simple wamp client library","0.1.0"},
 {wamper,"library of functions used for erwa, both client or router",
         "0.1.0"},
 {jsx,"a streaming, evented json parsing toolkit","2.6.2"},
 {msgpack,"MessagePack serializer/deserializer","git"},
 {pbkdf2,"Erlang PBKDF2 Key Derivation Function","git"},
 {gen_smtp,"A generic Erlang SMTP server/client framework",
           "0.12.0"},
 {ssl,"Erlang/OTP SSL application","8.2"},
 {public_key,"Public key infrastructure","1.4.1"},
 {crypto,"CRYPTO","4.0"},
 {asn1,"The Erlang ASN1 compiler version 5.0",[...]},
 {stdlib,[...],...},
 {kernel,...}]
(igs@ethrbh-VirtualBox)4> 

thanks for your help,
/Robi

**Comment by gomoripeti** [comment]
Hi Robi,

The 3rd argument (`Message`) of `lager:log/3` must be a string (or maybe iolist) not an arbitrary erlang term. 
https://github.com/erlang-lager/lager/blob/master/src/lager.erl#L168

Alternatively you can use `lager:log/4` the same way as `io:format` to format the term eg
```
 lager:log(info, self(), "~p", [{a,b,c}]).
```
https://github.com/erlang-lager/lager/blob/master/src/lager.erl#L175

**Comment by ethrbh** [comment]
szia Peti,

Thanks for the help. It is working, I tried. I close the ticket.

br,
/Robi

ps: Te dolgoztal regen az E///-nel, BP-n? Ha igen, akkor talan emlekszel ram, egyutt dolgoztunk az AXD301 projecten :-)
