### ISSUE TITLE
why use the func "lists:keymerge/3" when merge with the default options in the module "lager_file_backend"

### ISSUE THREAD

**Issue by HaotaoYang** [erlang-lager/lager#453]
It will be return two same key in the tuplelist, although it will not be affected to the result

**Comment by mrallen1** [comment]
Hi - thanks for the report, are you referring to [this function](https://github.com/erlang-lager/lager/blob/master/src/lager_file_backend.erl#L319-L326)?

**Comment by HaotaoYang** [comment]
oh, thanks, It's all right.
