### ISSUE TITLE
Not support Rebar3 ? 

### ISSUE THREAD

**Issue by vzzy** [erlang-lager/lager#454]
I use rebar2 is ok, but rebar3 is wrong with the same rebar.conf.
And OTP version is 20.3.6 on Mac OS 10.13.4.
`{erl_opts, [{parse_transform, lager_transform}, {lager_truncation_size, 1024}]}.

{deps, [
	{lager,{git, "https://github.com/erlang-lager/lager.git", {tag,"3.6.2"}}}
]}.`

Run with rebar3 show me below:
** exception error: undefined function lager:info/2

thanks.

**Comment by vzzy** [comment]
It's my fault, i do not clean the old beam.  Now, it's ok.  multi-version lager、rebar in my mac os.

**Comment by mrallen1** [comment]
OK, glad it's working for you!
