### ISSUE TITLE
Initial Erlang/OTP 21 compatibility

### ISSUE THREAD

**Issue by michaelklishin** [erlang-lager/lager#455]
## Background

This is a mostly placeholder issue for visibility. Team RabbitMQ is working towards [OTP 21 compatibility](https://github.com/rabbitmq/rabbitmq-server/issues/1616) and Lager is one dependency we have that is affected.

OTP 21 introduces a new logger and some assumption Lager has (e.g. about certain processes being available) are no longer true. This issue will be updated with details and proposed solutions/workarounds as @dumbbell and I dig them out.

The new logger is also raises the question about Lager's place in the post-OTP 21 ecosystem but let's keep that out of scope. At the very least there has to be an upgrade path for Lager users.

## Specific Issues

See OTP 21-rc.2 [release notes for details](http://erlang.org/download/otp_src_21.0-rc2.readme).

 * OTP-13295 deprecates `error_handler`. The claim of backwards compatibility only seems to be true to an extent. Lager depends on `error_handler` in several places, explicitly or implicitly: [one](https://github.com/erlang-lager/lager/blob/master/src/lager_app.erl#L229-L233), [two](https://github.com/erlang-lager/lager/blob/master/src/lager_handler_watcher.erl#L117), [three](https://github.com/erlang-lager/lager/blob/master/src/lager_app.erl#L256), and likely more.

**Comment by Vagabond** [comment]
Yeah, I think the big compatibility issue is around whether error_logger is running. I believe this stuff is limited to the lager_app file (I'm not sure how your second link is tied to error_logger).

We've had some discussion around how to handle this on IRC, but I think simply checking for the error_logger registered process before trying to install/remove/restore error_logger handlers would go a long way to solving this particular issue.

**Comment by Vagabond** [comment]
```Erlang/OTP 21 [RELEASE CANDIDATE 2] [erts-10.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Eshell V10.0  (abort with ^G)
1> application:ensure_all_started(lager).
{ok,[syntax_tools,compiler,goldrush,lager]}
2> lager:dispatch_log(lager_event, info, [{pid, self()}], "Hello from Erlang ~p", [erlang:system_info(otp_release)], 1024, safe).
ok
3> 08:40:30.455 [info] Hello from Erlang "21"```

This is the simplest possible change (I also found a fixed a bug). I will push up a branch shortly.

**Comment by mrallen1** [comment]
@Vagabond thanks for getting to this. I was planning to look at this issue today, actually, since OTP 21 seems imminent at this point.
