### ISSUE TITLE
exception error: undefined function lager:error/1

### ISSUE THREAD

**Issue by linrl3** [erlang-lager/lager#464]
```
Eshell V10.0.1  (abort with ^G)
1> lager:start().
ok
2> lager:error("what").
** exception error: undefined function lager:error/1
3> 
```
I can start lager but it shows that lager:error is undefined. Do I make something wrong? It's my first time to use Lager.

**Comment by Vagabond** [comment]
You need to configure the parse transform (or use the macros):

https://github.com/erlang-lager/lager#usage

**Comment by linrl3** [comment]
Yes, I add it into rebar.config, but it doesn't work.
