### ISSUE TITLE
Per module loglevel override

### ISSUE THREAD

**Issue by dcsommer** [erlang-lager/lager#465]
I'm not sure if this is already implemented, but it would be great to be able to override loglevel on a per-module basis. This is useful for on-the-fly debugging when you only want more information in one area.

**Comment by mrallen1** [comment]
Thanks for the comment - this is exactly the use case for the tracing facility in lager.  You can tell lager to always print messages for such and such a module and other arbitrary conditions of a log event.  You can read more about this feature here: https://github.com/erlang-lager/lager#tracing

Please let us know if that documentation is unclear or confusing. We can open a ticket to improve it based on your feedback.

**Comment by mrallen1** [comment]
I'm going to close this ticket - if you still need help with this issue, please open a new ticket.
