### ISSUE TITLE
Config error_logger_redirect not working with OTP 21

### ISSUE THREAD

**Issue by terry-xiaoyu** [erlang-lager/lager#481]
@mrallen1 Hi, the config `error_logger_redirect = true` not working on OTP 21. The messages logged using `error_logger` will still be printed to the screen.

I create a [demo project](https://github.com/terry-xiaoyu/lager_issue) for reproducing this issue. I am using lager 3.6.6.

**Comment by Vagabond** [comment]
You can do 

```erlang
logger:remove_handler(default).
```

To remove the default 'logger' handler that is printing to the console. Lager needs to be updated to connect to logger directly and not just boot up the legacy error_logger, but we haven't had the time to do that yet (I'm still not very familiar with logger at all).
