### ISSUE TITLE
No newlines in console backend file?

### ISSUE THREAD

**Issue by PiedPieper** [erlang-lager/lager#484]
Hi,

I'm writing to a file with the following configuration:

```
{handlers,
     [{lager_file_backend,
          [{file,"/var/log/project/console.log"},
           {level,debug},
           {formatter,lager_default_formatter},
           {formatter_config,
               [date," ",time," [",severity,"] ",pid," ",message]}]},
      {lager_file_backend,
          [{file,"/var/log/project/error.log"},
           {level,error},
           {formatter,lager_default_formatter},
           {formatter_config,
               [date," ",time," [",severity,"] ",pid," ",message]}]}]},

```

None of the files are written "prettily", in the sense that unlike in the console which each log line is separated by a newline, the files are un-separated. Is this intentional?

Using revision 81eaef0ce98fdbf64ab95665e3bc2ec4b24c7dac

**Comment by PiedPieper** [comment]
Here is an example..

> {{10,26,0,15},9042},[{cassandra_nodes,[{<<"10.26.0.15">>,9042}]},{included_applications,[]},{keyspace,...},...]}) at pid <0.900.0>2018-10-25 17:36:17.662 [debug] <0.881.0> Supervisor {<0.881.0>,cqerl_client_sup} started cqerl_client:start_link({{10,26,0,15},9042}, [{ssl,false},{keyspace,devices}], #Fun<cqerl.5.61291529>, {{{10,26,0,15},9042},[{cassandra_nodes,[{<<"10.26.0.15">>,9042}]},{included_applications,[]},{keyspace,...},...]}) at pid <0.901.0>2018-10-25 17:36:17.810 [debug] <0.881.0> Supervisor {<0.881.0>,cqerl_client_sup} started cqerl_client:start_link({{10,26,0,15},9042}, [{ssl,false},{keyspace,devices}], #Fun<cqerl.5.61291529>, {{{10,26,0,15},9042},[{cassandra_nodes,[{<<"10.26.0.15">>,9042}]},{included_applications,[]},{keyspace,...},...]}) at pid <0.902.0>2018-10-25 17:36:18.132 [debug] <0.874.0> Supervisor cqerl_sup started cqerl_cluster:start_link() at pid <0.880.0>2018-10-25 17:36:18.132 [info] <0.712.0> Application cqerl started on node 'SMDPP_PROXY@10.26.0.196'2018-10-25 17:36:18.132 [info] <0.712.0> Application cowlib started on node 'SMDPP_PROXY@10.26.0.196'2018-10-25 17:36:18.133 [debug] <0.907.0> Supervisor ranch_sup started ranch_server:start_link() at pid <0.908.0>2018-10-25 17:36:18.133 [info] <0.712.0> Application ranch started on node 'SMDPP_PROXY@10.26.0.196'2018-10-25 17:36:18.133 [info] <0.712.0> Application mochiweb_util started on node 'SMDPP_PROXY@10.26.0.196'2018-10-25 17:36:18.133 [info] <0.712.0> Application restc started on node 'SMDPP_PROXY@10.26.0.196'2018-10-25 17:36:18.133 [info] <0.712.0> Application lager_syslog started on node 'SMDPP_PROXY@10.26.0.196'2018-10-25 17:36:18.134 [debug] <0.915.0> Supervisor ibrowse_sup started ibrowse:start_link() at pid <0.916.0>2018-10-25 17:36:18.134 [info] <0.712.0> Application ibrowse started on node 'SMDPP_PROXY@10.26.0.196'2018-10-25 17:36:18.134 [info] <0.712.0> Application gen_smtp started on node 'SMDPP_PROXY@10.26.0.196'2018-10-25 17:36:18.134 [info] <0.712.0> Application prof_ops started on node 'SMDPP_PROXY@10.26.0.196'

**Comment by PiedPieper** [comment]
As you can see, there are no new lines... no idea why.

**Comment by shamis** [comment]
@PiedPieper as mentioned in the [README](https://github.com/erlang-lager/lager#custom-formatting), could you please try using `"\n"` in the formatter_configas following
```erlang
{handlers,
     [{lager_file_backend,
          [{file,"/var/log/project/console.log"},
           {level,debug},
           {formatter,lager_default_formatter},
           {formatter_config,
               [date," ",time," [",severity,"] ",pid," ",message, "\n"]}]},
      {lager_file_backend,
          [{file,"/var/log/project/error.log"},
           {level,error},
           {formatter,lager_default_formatter},
           {formatter_config,
               [date," ",time," [",severity,"] ",pid," ",message,"\n"]}]}]},
```

**Comment by PiedPieper** [comment]
This worked. Thank you.

**Comment by mrallen1** [comment]
Going to close this issue now. If you need further help with it, please open a new ticket.
