### ISSUE TITLE
Lager seems to be logging the same message to the log file multiple times

### ISSUE THREAD

**Issue by nitinjain1105** [erlang-lager/lager#495]
Hi,

I am observing the issue where Lager seems to be logging the same message multiple times. This is blowing up my disk space very quickly, please help.

I am using lager from with in my Elixir Application - 
```
defp deps do
   [
       {:lager, "~> 3.2"}
   ]
end
```

**Comment by mrallen1** [comment]
Hi, sorry you're having trouble. By design lager will write all the messages it receives into its sink mailbox to disk (if configured to do so). 

Can you provide some more information about what is generating these messages and the behavior that you desire.

**Comment by nitinjain1105** [comment]
I am creating dynamic sinks in my application using the below function - 
```
:lager_app.configure_sink(lager_sink_name,
        level: :info,
        async_threshold: 500,
        async_threshold_window: 50,
        handlers: [
          lager_file_backend: [
            file: log_file_name,
            level: :info,
          ]
        ]
      )
```

and then log the message using the below function:

`:lager.log(lager_sink_name, level, [], msg, [])`

**Comment by mrallen1** [comment]
What version of Erlang and elixir are you using? I think your message is being processed by multiple lager handlers.

**Comment by nitinjain1105** [comment]
elixir 1.8.0
erlang 21.2

sorry I didn't understand when you say "message is being processed by multiple lager handlers."

**Comment by mrallen1** [comment]
The way lager works is by installing [gen_event][1] handlers to process incoming log messages. These handlers store the message to disk or output it to the console. If you install your own event handler using `configure_sink` that means the default event handlers are still running too, which means they will *also* process any log messages which arrive. Hence, duplicates.

[1]: https://learnyousomeerlang.com/event-handlers

**Comment by nitinjain1105** [comment]
but I made sure that any particular log should go to only one sink, I am specifying the lager_sink_name while logging

`:lager.log(lager_sink_name, level, [], msg, [])`

**Comment by mrallen1** [comment]
No, sorry, I don't know what else to suggest.

**Comment by lukebakken** [comment]
@nitinjain1105 the easiest way to get assistance with this issue is to provide runnable code to reproduce it, ideally in the form of a git repository so that it can be cloned, compiled, and run. Without that, this issue should just be closed.
