### ISSUE TITLE
Log Rotation not happening on NAS

### ISSUE THREAD

**Issue by nitinjain1105** [erlang-lager/lager#498]
Hi,

I have set the log location to be my NAS(Network Attached Storage) directory. Now when the log rotation triggers (I have set the trigger $D0) the previous file disappears and the new file gets created. 

There is no history of log files available. Below is my config values -
```
          size: 100 * 1024 * 1024,
          date: '$D0',
          count: 10
```

Please help!!

**Comment by Vagabond** [comment]
Can you give more information what operating system you're using and if this happens if you don't log to the NAS?

Also, to clarify you only ever have one log file, when the rotation triggers the previous file is *deleted* and a new one is created?

**Comment by nitinjain1105** [comment]
Rotation works fine when I log to my project directory, but when I log to NAS, previous log files starts disappearing. 

Yes I only have only one log file at any given time, when the rotation triggers the previous file is deleted and a new one is created

I am running this on Windows. My Elixir application is running as a windows service. 

Thanks
Nitin

**Comment by Vagabond** [comment]
What happens if you disable log rotation (or I guess leave it as is) and rotate the file yourself by renaming the active log file?

**Comment by nitinjain1105** [comment]
Yes if I manually rename the file then it stays there

**Comment by Vagabond** [comment]
are you using the latest release of lager? I merged some windows rotation stuff recently. I don't have access to a windows machine with NAS, so I'm a bit limited in how I can debug this.

**Comment by nitinjain1105** [comment]
Thanks..upgrading lager version helped

**Comment by Vagabond** [comment]
Thanks for letting us know. Glad it worked out.
