### ISSUE TITLE
Resolve new dialyzer errors

### ISSUE THREAD

**Issue by vikger** [erlang-lager/lager#500]
Hi,

The following errors were produced when running dialyzer on the latest lager on master branch

```
$ make dialyzer
test -d deps || ./rebar get-deps
./rebar compile
==> goldrush (compile)
==> lager (compile)
Compiled src/lager_util.erl
Compiled src/lager_app.erl
Compiled src/lager_handler_watcher.erl
Compiled src/lager.erl
Compiled src/error_logger_lager_h.erl
Compiled src/lager_rotator_default.erl
Compiled src/lager_file_backend.erl
  Checking whether the PLT /Users/viktorgergely/.combo_dialyzer_plt is up-to-date... yes
done (passed successfully)
 yes
done (passed successfully)
  Checking whether the PLT .local_dialyzer_plt is up-to-date... yes
done (passed successfully)
 yes
done (passed successfully)
==> lager (dialyzer)
error_logger_lager_h.erl:367: The variable Invalid can never match since previous clauses completely covered the type 'logged' | 'no_log'
lager.erl:694: Expression produces a value of type 'ok' | {'error','lager_not_running'}, but this value is unmatched
lager_app.erl:170: Expression produces a value of type 'ok' | {'error',_}, but this value is unmatched
lager_file_backend.erl:198: Expression produces a value of type 'ok' | #state{name::string(),level::{'mask',integer()},fd::'undefined' | pid() | {'file_descriptor',atom(),_},inode::'undefined' | integer(),flap::boolean(),size::integer(),date::'undefined' | string(),count::integer(),rotator::atom(),shaper::#lager_shaper{hwm::'undefined' | pos_integer(),mps::non_neg_integer(),lasttime::{_,_,_},dropped::non_neg_integer(),flush_queue::boolean(),flush_threshold::integer(),timer::reference(),filter::fun()},formatter::atom(),sync_on::{'mask',integer()},check_interval::non_neg_integer(),sync_interval::non_neg_integer(),sync_size::non_neg_integer(),last_check::{non_neg_integer(),non_neg_integer(),non_neg_integer()}}, but this value is unmatched
lager_handler_watcher.erl:78: Expression produces a value of type {'error',_} | {'ok',timer:tref()}, but this value is unmatched
lager_handler_watcher.erl:101: Expression produces a value of type {'error',_} | {'ok',timer:tref()}, but this value is unmatched
lager_rotator_default.erl:80: Expression produces a value of type 'ok' | {'error',atom()}, but this value is unmatched
lager_util.erl:533: Expression produces a value of type 'false' | non_neg_integer(), but this value is unmatched
make: *** [dialyzer-run] Error 1
```

The first issue seems to be valid, the last clause in error_logger_lager_h can be removed.
With the rest of the errors, it needs to be checked what is the best way to handle them, either
(1) add "_ =" before the function call to indicate that the return value can be ignored, or
(2) match with the successful return value (ususally 'ok') and let it crash when an unexpected return occurs.

Regards,
Viktor

Issue occurred on commit 4ffdf0dbef53304bc0e958a00776bf0650de8c8b with Erlang/OTP 21.3.8.1.

**Comment by mrallen1** [comment]
Thanks for opening an issue! I'll tag it as "help wanted" and maybe someone will pick it up!

**Comment by vikger** [comment]
Pull request #501 has been created. Please review the solution.

**Comment by vikger** [comment]
CI failed with one of the 3 OTP versions. How is it possible to retrigger the tests?
Also, testing locally with OTP 22.0 there are some errors with crash_fsm/crash_statem suites that need to be revised.

**Comment by mrallen1** [comment]
I suppose we should get 22.0 in the test package but I'm not sure anyone is prepared to deal with the fsm/statem breakages yet.

**Comment by vikger** [comment]
Thanks for the merge! 2 questions about the way-of-working in this repo:
- Is it ok that I push the changes to the master branch on my fork before the review and merge of the pull request?
- How can I retrigger CI test for my commit? There seems to have been an environment issue when testing with OTP 21.

**Comment by mrallen1** [comment]
1. Sure, I think that's fine
2. Only project maintainers can tell travis to re-run a failed test.

Thanks again!
