### ISSUE TITLE
lager does not write to NAS when running the application as a windows service

### ISSUE THREAD

**Issue by nitinjain1105** [erlang-lager/lager#504]
Hi,

Lager seems to not writing the log file to NAS when I run my application as a windows service in background mode.

P.S. it works fine though when I run my application in foreground mode

**Comment by nitinjain1105** [comment]
Hi @mrallen1 

Can you please look into this. This is becoming a bottleneck for us in Production. Many thanks in advance

- 
Nitin

**Comment by lukebakken** [comment]
More than likely you are running into an issue like this: https://stackoverflow.com/questions/3622089/windows-service-cant-access-network-share

@mrallen1 I recommend closing this stale issue as reproduction steps aren't provided.

**Comment by mrallen1** [comment]
Yeah going to close this for now.
