### ISSUE TITLE
No functions lager:info and lager:error mentioned in the docs

### ISSUE THREAD

**Issue by raphapassini** [erlang-lager/lager#505]
Hello dear contributor :)

I'm newby in Erlang so pardon if it's a silly question, but after reading the code and the documentation I could use those functions mentioned in the doc:https://github.com/erlang-lager/lager#usage, I rather have to use `lager:log(info, Pid, Message)`. 

Maybe I'm missing something or maybe the documentation is outdated, let me know in either case so maybe I can contribute to enhance the documentation.

Thanks for the nice work on handling logs :)

**Comment by mrallen1** [comment]
You are correct that `lager:info` and `lager:error` do not actually exist as functions in this application. They are syntactic sugar for calling `lager:log` with some pre-filled parameters and the the `info` and `error` pieces are transformed during compilation by the Erlang compiler following the code inside of the `lager_transform.erl` module.

**Comment by mrallen1** [comment]
Going to close this issue now. If you still need help, please open a new issue.
