### ISSUE TITLE
AppVeyor build is not accessible

### ISSUE THREAD

**Issue by lukebakken** [erlang-lager/lager#511]
For some reason, the following link doesn't work -

https://ci.appveyor.com/project/erlang-lager/lager

I get "Project not found or access denied"

I was planning on adding a build status indicator to the README document.

**Comment by mrallen1** [comment]
I did it as https://ci.appveyor.com/project/mrallen1/lager
Which I guess isn't ideal but I'm not sure how to get the URL aligned with the project on github
    On Monday, August 12, 2019, 9:13:33 AM CDT, Luke Bakken <notifications@github.com> wrote:  
 
 
For some reason, the following link doesn't work -

https://ci.appveyor.com/project/erlang-lager/lager

I get "Project not found or access denied"

I was planning on adding a build status indicator to the README document.

**Comment by lukebakken** [comment]
Once you log into AppVeyor using your GitHub credentials, you should be able to "choose" your organization via a drop-down in the title bar. My default org is my user account org, but the others in which I'm an admin show up in the drop-down. I suspect you'll see `erlang-lager` there.

**Comment by mrallen1** [comment]
I see it, and I see the project, but when I click "add" it seems to keep the results under my account and not the github org name.

**Comment by lukebakken** [comment]
Hmm, perhaps you need to delete the build under your account first? It's not a big deal to use the `mrallen1` build either, now that I know where it is. Don't spend a lot of time on this :-)

**Comment by lukebakken** [comment]
Or, if you'd like, you could add me to `erlang-lager` for as long as it takes to figure this out!
