### ISSUE TITLE
Can we set log_root dynamically

### ISSUE THREAD

**Issue by nitinjain110588** [erlang-lager/lager#526]
Hi,

I am trying to set value of log_root dynamically from source code but it seems not working. 

LogRoot = "my/custom/directory",
application:set_env(lager, log_root, LogRoot).

Please advise.

**Comment by lukebakken** [comment]
That should work if you do it _before_ the `lager` application starts. Have you tried that?

**Comment by nitinjain110588** [comment]
@lukebakken if I try to set _log_root_ before starting lager, then it is not successfully setting. 

LogRoot = "my/custom/directory",
application:set_env(lager, log_root, LogRoot).
lager:start()

P.S. - lager configurations are in **myApp.config**

**Comment by aboroska** [comment]
@nitinjain110588 Unfortunately `application:set_env/3`  only works when an app is already loaded. 

    application:load(lager), % Or application:stop(lager) if already started
    LogRoot = "my/custom/directory",
    application:set_env(lager, log_root, LogRoot).
    lager:start()

**Comment by nitinjain110588** [comment]
Thank you @aboroska
