### ISSUE TITLE
Here's a suggestion 

### ISSUE THREAD

**Issue by SisMaker** [erlang-lager/lager#553]
in the 
         lager_backend_throttle.erl module 
 the fun
         handle_event({log, _Message}, State) ->    {message_queue_len, Len} = erlang:process_info(self(), message_queue_len), ...
use the erlang:process_info(self(), message_queue_len), The performance is poor when multiple processes are called,
Is there any other way to replace it?

**Comment by mrallen1** [comment]
I'd be happy to review a patch implementing your suggestion.

**Comment by SisMaker** [comment]
> I'd be happy to review a patch implementing your suggestion.

i have a idea, use persistent_term and atomics to cout log num
